import 'package:flutter/material.dart';

const appBarColor = Color(0xFFD14848);
const colorTitleAmber = Color(0xFFF47F3E);
const colorBorder =Colors.black26;
const colorTitleBold = Color(0xFF41444F);
const colorTitleMedium = Color(0xFF818493);
const colorButtonCart = Color(0xFFBFBFBF);
const colorTextBold = Color(0xFFC1BFBA);
const colorRatingStar = Color(0xFFFF2C55);
const colorTextPrice = Color(0xFF2C3E50);
const colorTextSaleOff = Color(0xFFF7F700);
const colorMainBackground = Color(0xFFF5F6F8);
const colorPriceRoom = Color(0xFF29C254);
const colorCartItemBackground = Color(0xFFF4F9F7);
const colorBackgroundMomo=Color(0xFFFDADD4);
const colorBorderMomo = Color(0xFFAE2070);
const colorBackgroundVNPay=Color(0xFF9AE5EF);
const colorBorderVNPay = Color(0xFF005AAB);
const colorItemHistoryBooking = Color(0xFFF8F9FB);